[package]
name = "leetcode-1248"
version = "0.1.0"
authors = ["Yuan Yu <yuany_2d1@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
